{
 "title": "Ollama Log Exporter Dashboard",
 "tags": [
  "ollama",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Количество запросов к Ollama",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(ollama_requests_total{job=\"ollama\", status=\"200\"}[5m])) by (endpoint, method, model)",
     "legendFormat": "{{endpoint}} {{method}} {{model}}"
    }
   ]
  },
  {
   "title": "Ошибки Ollama (4xx, 5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(ollama_requests_total{job=\"ollama\", status=~\"[45]..\"}[5m])) by (status, model)",
     "legendFormat": "Ошибка {{status}} ({{model}})"
    }
   ]
  },
  {
   "title": "Время обработки запроса (latency, 95-й перцентиль)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ollama_request_duration_seconds_bucket[5m])) by (le, endpoint, model))",
     "legendFormat": "{{endpoint}} ({{model}})"
    }
   ]
  },
  {
   "title": "Активность за последние 5 минут",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(ollama_requests_total{job=\"ollama\"}[5m])) by (ip, endpoint, method, model)"
    }
   ]
  },
  {
   "title": "Конфигурация Ollama",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "ollama_info{job=\"ollama\"}"
    }
   ]
  }
 ]
}